version: '3.8'

services:
  entersys-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entersys-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - entersys-network

  nginx:
    image: nginx:alpine
    container_name: entersys-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - entersys-frontend
    restart: unless-stopped
    networks:
      - entersys-network

networks:
  entersys-network:
    driver: bridge